[package]
name = "vespera-file-ops"
version = "0.1.0"
edition = "2021"
description = "High-performance file operations for MCP servers with Python bindings"

[lib]
name = "vespera_file_ops"
crate-type = ["rlib", "cdylib"]

[features]
default = ["python-bindings"]
python-bindings = ["pyo3"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"], optional = true }
tokio = { version = "1.0", features = ["fs", "rt-multi-thread"] }
memmap2 = "0.9"
walkdir = "2.4"
globset = "0.4"
grep = "0.2"
regex = "1.10"
aho-corasick = "1.1"
camino = "1.1"
thiserror = "1.0"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
proptest = "1.4"

[[bench]]
name = "edit_benchmarks"
harness = false

[build-dependencies]
pyo3-build-config = "0.22"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"