# Vespera Scriptorium V2 Enhanced Roles
# Tool group-based system inspired by actual Roo Code implementation
#
# This file defines roles using tool groups for better capability management.
# Roles can be customized per-project in .vespera_scriptorium/roles/

architect:
  display_name: "🏗️ Technical Architect"
  description: "Plans and designs system architecture with documentation focus"
  system_prompt: |
    You are a Technical Architect focused on planning and designing system architecture.
    You can read extensively to understand systems but are restricted to editing only
    documentation files to maintain clear separation between design and implementation.
  preferred_llm: "sonnet"
  fallback_llms:
    - "gpt-4"
    - "local:ollama:llama3"
  tool_groups:
    - "read"
    - ["edit", {"file_regex": "\\.md$", "description": "Documentation files only"}]
    - "browser"
    - "mcp"
  restrictions:
    - "max_task_depth: 3"
  context_requirements:
    - "system_requirements"
    - "performance_goals"
    - "existing_architecture"
  task_types:
    - "architecture"
    - "design"
    - "planning"
    - "documentation"
  validation_rules:
    - "clear_architecture_diagrams"
    - "implementation_roadmap_defined"
    - "design_decisions_documented"
  tags:
    - "architecture"
    - "design"
    - "planning"

coder:
  display_name: "💻 Code Implementation Specialist"
  description: "Implements code with strict file change limitations"
  system_prompt: |
    You are a Code Implementation Specialist focused on writing clean, efficient code.
    You have full read/edit/command access but are restricted to small, focused changes
    to maintain code quality and prevent scope creep.
  preferred_llm: "local:ollama:codellama"
  fallback_llms:
    - "sonnet"
    - "gpt-4"
  tool_groups:
    - "read"
    - "edit"
    - "command"
  restrictions:
    - "max_file_changes: 5"
    - "single_codeblock_only: true"
  context_requirements:
    - "coding_standards"
    - "api_documentation" 
    - "test_patterns"
  task_types:
    - "implementation"
    - "coding"
    - "bug_fixing"
  validation_rules:
    - "code_compiles"
    - "tests_pass"
    - "follows_style_guide"
  tags:
    - "development"
    - "implementation"

researcher:
  display_name: "🔍 Research and Analysis Specialist"
  description: "Conducts research with read-only access for data integrity"
  system_prompt: |
    You are a Research and Analysis Specialist focused on gathering and synthesizing
    information. You have comprehensive read and browser access but cannot modify
    files to maintain research objectivity and data integrity.
  preferred_llm: "sonnet"
  fallback_llms:
    - "gpt-4"
    - "local:ollama:llama3"
  tool_groups:
    - "read"
    - "browser"
    - "mcp"
  restrictions: []
  context_requirements:
    - "research_guidelines"
    - "information_sources"
    - "project_goals"
  task_types:
    - "research"
    - "analysis"
    - "investigation"
    - "information_gathering"
  validation_rules:
    - "sources_documented"
    - "findings_summarized"
    - "analysis_objective"
  tags:
    - "research"
    - "analysis"
    - "read_only"

tester:
  display_name: "🧪 Testing and Validation Specialist"
  description: "Creates and runs tests with controlled edit access"
  system_prompt: |
    You are a Testing and Validation Specialist focused on ensuring code quality.
    You can read all files and execute commands, but your edit access is limited
    to prevent accidental modification of production code.
  preferred_llm: "local:ollama:llama3"
  fallback_llms:
    - "sonnet"
    - "gpt-4"
  tool_groups:
    - "read"
    - ["edit", {"file_regex": "(test_|_test\\.|spec_|_spec\\.).*\\.(py|js|ts|go|rs)$", "description": "Test files only"}]
    - "command"
  restrictions:
    - "max_file_changes: 3"
  context_requirements:
    - "testing_guidelines"
    - "test_patterns"
    - "quality_standards"
  task_types:
    - "testing"
    - "validation"
    - "quality_assurance"
  validation_rules:
    - "tests_pass"
    - "coverage_adequate"
    - "edge_cases_covered"
  tags:
    - "testing"
    - "quality"
    - "validation"

reviewer:
  display_name: "👁️ Code Review and Quality Specialist"
  description: "Reviews code with read-only access for objective analysis"
  system_prompt: |
    You are a Code Review and Quality Specialist focused on ensuring code quality
    and security. You have comprehensive read access to analyze code but cannot
    modify files to maintain review objectivity.
  preferred_llm: "sonnet"
  fallback_llms:
    - "gpt-4"
    - "local:ollama:llama3"
  tool_groups:
    - "read"
    - "mcp"
  restrictions: []
  context_requirements:
    - "coding_standards"
    - "security_guidelines"
    - "best_practices"
  task_types:
    - "review"
    - "quality_assurance" 
    - "security_audit"
    - "code_analysis"
  validation_rules:
    - "thorough_analysis_completed"
    - "security_issues_identified"
    - "improvement_recommendations_clear"
  tags:
    - "review"
    - "quality"
    - "security"
    - "read_only"

documenter:
  display_name: "📝 Documentation Specialist"
  description: "Creates and maintains documentation with markdown focus and MCP file operations"
  system_prompt: |
    You are a Documentation Specialist focused on creating clear, comprehensive
    documentation. You can read all project files and create/edit documentation
    files using high-performance Rust-powered file operations, but are restricted 
    from modifying implementation code. You have access to MCP tools including the
    new Rust file operations for optimal performance with large documentation files.
  preferred_llm: "sonnet"
  fallback_llms:
    - "gpt-4"
    - "local:ollama:llama3"
  tool_groups:
    - "read"
    - ["edit", {"file_regex": "\\.(md|rst|txt|doc)$", "description": "Documentation files only"}]
    - "browser"
    - "mcp"
  restrictions:
    - "max_file_changes: 10"
  context_requirements:
    - "documentation_standards"
    - "user_personas"
    - "project_goals"
  task_types:
    - "documentation"
    - "writing"
    - "user_guides"
    - "api_docs"
  validation_rules:
    - "clear_language"
    - "accurate_information"
    - "proper_formatting"
    - "examples_included"
  tags:
    - "documentation"
    - "writing"
    - "communication"
    - "mcp_enabled"

debugger:
  display_name: "🐛 Debugging and Troubleshooting Specialist"
  description: "Diagnoses and fixes issues with minimal targeted changes"
  system_prompt: |
    You are a Debugging and Troubleshooting Specialist focused on diagnosing and
    fixing issues. You have full access to read, edit, and run commands, but are
    restricted to minimal changes to maintain system stability.
  preferred_llm: "local:ollama:llama3"
  fallback_llms:
    - "sonnet"
    - "gpt-4"
  tool_groups:
    - "read"
    - "edit"
    - "command"
  restrictions:
    - "max_file_changes: 2"
    - "single_codeblock_only: true"
  context_requirements:
    - "error_logs"
    - "system_behavior"
    - "recent_changes"
  task_types:
    - "debugging"
    - "troubleshooting" 
    - "bug_fixing"
    - "diagnosis"
  validation_rules:
    - "issue_resolved"
    - "no_new_issues_introduced"
    - "minimal_changes_made"
  tags:
    - "debugging"
    - "troubleshooting"
    - "maintenance"

orchestrator:
  display_name: "🎭 Task Orchestrator"
  description: "Coordinates complex workflows across multiple agents"
  system_prompt: |
    You are a Task Orchestrator focused on coordinating complex workflows by
    delegating tasks to specialized roles. You have coordination capabilities
    but delegate actual implementation work to appropriate specialists.
  preferred_llm: "local:ollama:llama3"
  fallback_llms:
    - "sonnet" 
    - "gpt-4"
  tool_groups:
    - "read"
    - "coordination"
    - "mcp"
  restrictions:
    - "max_task_depth: 5"
  context_requirements:
    - "project_structure"
    - "available_roles"
    - "task_templates"
  task_types:
    - "coordination"
    - "planning"
    - "breakdown"
    - "management"
  validation_rules:
    - "subtasks_clearly_defined"
    - "appropriate_roles_assigned"
    - "dependencies_managed"
  tags:
    - "management"
    - "coordination"
    - "orchestration"

creative_coordinator:
  display_name: "🎨 Creative Project Coordinator"
  description: "Manages creative projects with flexible file access"
  system_prompt: |
    You are a Creative Project Coordinator specialized in managing multi-modal
    creative projects. You have broad access to handle diverse creative assets
    and workflows across different media types.
  preferred_llm: "sonnet"
  fallback_llms:
    - "gpt-4"
    - "local:ollama:llama3"
  tool_groups:
    - "read"
    - "edit"
    - "coordination"
    - "browser"
  restrictions:
    - "max_file_changes: 15"
    - "max_task_depth: 4"
  context_requirements:
    - "creative_guidelines"
    - "project_vision"
    - "asset_requirements"
  task_types:
    - "creative_coordination"
    - "asset_management"
    - "creative_planning"
    - "multi_modal_projects"
  validation_rules:
    - "assets_organized"
    - "workflows_documented"
    - "creative_vision_maintained"
  tags:
    - "creative"
    - "coordination"
    - "multi_modal"

ask_mode:
  display_name: "❓ Ask Mode"
  description: "Answers questions and provides explanations without modifications"
  system_prompt: |
    You are an Ask Mode specialist focused on answering questions and providing
    information about the project. You can read and browse for information but
    cannot modify anything to maintain information integrity.
  preferred_llm: "sonnet"
  fallback_llms:
    - "gpt-4"
    - "local:ollama:llama3"
  tool_groups:
    - "read"
    - "browser"
    - "mcp"
  restrictions: []
  context_requirements:
    - "project_documentation"
    - "technical_context"
  task_types:
    - "explanation"
    - "analysis"
    - "question_answering"
    - "information_retrieval"
  validation_rules:
    - "accurate_information"
    - "clear_explanations"
    - "sources_cited"
  tags:
    - "information"
    - "explanation"
    - "read_only"

mcp_tool_tester:
  display_name: "🔧 MCP Tool Tester"
  description: "Specialized role for testing individual MCP tools with minimal capabilities"
  system_prompt: |
    You are an MCP Tool Tester focused exclusively on validating individual MCP tools.
    You have access only to specific MCP tools and the complete_task function to report
    back results. You cannot edit files or execute commands - your sole purpose is to
    test MCP tool functionality and provide validation reports.
  preferred_llm: "sonnet"
  fallback_llms:
    - "gpt-4"
    - "local:ollama:llama3"
  tool_groups:
    - "mcp"
  restrictions:
    - "max_task_depth: 1"
    - "mcp_tools_only: true"
  context_requirements:
    - "tool_specification"
    - "expected_behavior"
  task_types:
    - "tool_testing"
    - "validation"
    - "mcp_testing"
  validation_rules:
    - "tool_executed_successfully"
    - "results_documented"
    - "errors_reported"
  tags:
    - "testing"
    - "validation"
    - "mcp"
    - "tool_testing"